## $Id: Makefile.cmd_epcr,v 1.4 2007/07/05 16:06:04 rotmistr Exp $
########################################################################
##
##                            PUBLIC DOMAIN NOTICE
##               National Center for Biotechnology Information
##
##  This software/database is a "United States Government Work" under the
##  terms of the United States Copyright Act.  It was written as part of
##  the author's official duties as a United States Government employee and
##  thus cannot be copyrighted.  This software/database is freely available
##  to the public for use. The National Library of Medicine and the U.S.
##  Government have not placed any restriction on its use or reproduction.
##
##  Although all reasonable efforts have been taken to ensure the accuracy
##  and reliability of the software and data, the NLM and the U.S.
##  Government do not and cannot warrant the performance or results that
##  may be obtained by using this software or data. The NLM and the U.S.
##  Government disclaim all warranties, express or implied, including
##  warranties of performance, merchantability or fitness for any particular
##  purpose.
##
##  Please cite the author in any work or product based on this material.
##
########################################################################

srcdir = .
include $(srcdir)/stand/config.mk

SRC_FILES = e-PCR_main 
SRC = $(SRC_FILES:%=$(srcdir)/%.cpp)
OBJ = $(SRC_FILES:%=$(objdir)/%.o)
HDR = 
LIB = epcr

#LIBNAME = epcr
TARGET = $(tgtdir)/e-PCR

target: $(TARGET)

install:
	cp $(TARGET) $(BINDIR)

install-lib:

$(TARGET): $(OBJ) $(LIB:%=$(tgtdir)/lib%.a)
	-rm -f $@
	$(CXX) $(LDFLAGS) -o $@ $(OBJ) $(LIB:%=-l%)

$(objdir)/e-PCR_main.o: 		$(srcdir)/e-PCR_main.cpp

depend: 
	$(CXX) $(CXXFLAGS) -M $(SRC) | $(FIXCMD) > $(tgtdir)/cmdepcr_depend.mk

-include $(tgtdir)/cmdepcr_depend.mk

########################################################################
## $Log: Makefile.cmd_epcr,v $
## Revision 1.4  2007/07/05 16:06:04  rotmistr
## Made things compileable by MS Visual C++ 8.0
##
## Revision 1.3  2004/03/30 21:39:30  rotmistr
## Fixed build arguments usage
##
## Revision 1.2  2004/02/04 21:23:46  rotmistr
## - gcc-3.3.2 compatible
## - better postfiltering for reverse-e-PCR for discontiguos words
## - cgi added, that supports:
##  -- contig to chromosome mapping
##  -- simple mapviewer links
##  -- unists links
##  -- discontiguos words
##
## Revision 1.1.1.1  2003/12/23 18:17:28  rotmistr
## Package that includes e-PCR, reverse e-PCR, and sequence data preparation
## program for reverse e-PCR looks ready
##
## Revision 1.5  2003/12/01 12:29:36  rotmistr
## Reverse PCR wordhash builder in progress
##
## Revision 1.4  2003/11/21 23:26:36  rotmistr
## Almost compilable
##
## Revision 1.3  2003/11/20 18:27:32  rotmistr
## Sample files updated
## Program does not crush
##
## Revision 1.2  2003/11/20 02:12:28  rotmistr
## Fixed id, log tags and copyright notice
##
########################################################################
